### ISSUE TITLE
Odd exception in Timers_Refresh

### ISSUE THREAD

**Issue by astorDev** [astorDev/Astor.Background#13]
In Timers_Refresh occurs odd exception:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Astor.Background.Management.Service.Timers.Timers.Ensure(TimesAction timesAction, Action`1 action) in /src/Astor.Background.Management.Service/Timers/Timers.cs:line 61
   at Astor.Background.Management.Service.Controllers.TimersController.RefreshAsync()
   
   which is sent to telegram, but has no visible effect on behaviour

**Comment by astorDev** [comment]
In logs when updating timers list there is something strange: after removing there are no log of adding and it's added only in next cycle - maybe it's due to bug above

**Comment by astorDev** [comment]
Fixed by making ToArray() in Get
